-- ============================================================
-- Migration: 006 — Create order_items
-- Replaces: orders.items_detail (jsonb)
-- Enables: per-product analytics, BI, inventory tracking,
--          revenue reports, top-selling products, margin analysis
-- ============================================================

-- ------------------------------------------------------------
-- 1. Create order_items table
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.order_items (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Relationship: CASCADE delete keeps referential integrity
  -- (deleting an order removes its items)
  order_id              bigint      NOT NULL REFERENCES public.orders(id)   ON DELETE CASCADE,

  -- SET NULL on product delete: preserves the order history even
  -- when the product is soft-deleted or hard-deleted.
  -- product_name_snapshot ensures the order record is self-contained.
  product_id            bigint               REFERENCES public.products(id) ON DELETE SET NULL,

  -- Snapshot columns: capture the product state at purchase time.
  -- Critical for historical accuracy — product price/name may change later.
  product_name_snapshot text        NOT NULL,
  sku_snapshot          text,

  quantity              integer     NOT NULL,
  unit_price            numeric(12,2) NOT NULL,

  -- Generated column: always consistent with quantity × unit_price.
  -- Cannot be inserted/updated directly — computed by the database.
  total_price           numeric(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,

  created_at            timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT order_items_quantity_positive        CHECK (quantity > 0),
  CONSTRAINT order_items_unit_price_non_negative  CHECK (unit_price >= 0)
);

-- ------------------------------------------------------------
-- 2. Indexes
-- ------------------------------------------------------------

-- FK indexes (prevent sequential scans on joins)
CREATE INDEX IF NOT EXISTS idx_order_items_order_id
  ON public.order_items (order_id);

CREATE INDEX IF NOT EXISTS idx_order_items_product_id
  ON public.order_items (product_id)
  WHERE product_id IS NOT NULL;

-- Analytics: top-selling products
CREATE INDEX IF NOT EXISTS idx_order_items_product_id_quantity
  ON public.order_items (product_id, quantity);

-- ------------------------------------------------------------
-- 3. Migrate data from items_detail jsonb
-- Safely handles: null items_detail, malformed JSON elements,
-- non-numeric product_ids, zero/null quantities.
-- ------------------------------------------------------------

INSERT INTO public.order_items (
  order_id,
  product_id,
  product_name_snapshot,
  quantity,
  unit_price
)
SELECT
  o.id                                          AS order_id,
  NULLIF(trim(item->>'product_id'), '')::bigint AS product_id,
  COALESCE(NULLIF(trim(item->>'name'), ''), 'Produto')
                                                AS product_name_snapshot,
  GREATEST(COALESCE((item->>'quantity')::integer, 1), 1)
                                                AS quantity,
  GREATEST(COALESCE((item->>'price')::numeric(12,2), 0), 0)
                                                AS unit_price
FROM
  public.orders o,
  jsonb_array_elements(o.items_detail) AS item
WHERE
  o.items_detail IS NOT NULL
  AND jsonb_typeof(o.items_detail) = 'array'
  AND jsonb_array_length(o.items_detail) > 0
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- 4. RLS
-- ------------------------------------------------------------

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Users can read items from their own orders; admins read all.
CREATE POLICY order_items_select
  ON public.order_items
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.orders
      WHERE orders.id = order_items.order_id
        AND (orders.customer_id = auth.uid() OR public.is_admin())
    )
  );

-- Users can insert items only for their own orders (checkout flow).
-- Admins can insert for any order.
CREATE POLICY order_items_insert
  ON public.order_items
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.orders
      WHERE orders.id = order_id
        AND orders.customer_id = auth.uid()
    )
  );

-- Only admins can update or delete order items (corrections/refunds).
CREATE POLICY order_items_update
  ON public.order_items
  FOR UPDATE TO authenticated
  USING (public.is_admin());

CREATE POLICY order_items_delete
  ON public.order_items
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- ------------------------------------------------------------
-- 5. Grants
-- ------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_items TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE order_items_id_seq TO authenticated;

-- ------------------------------------------------------------
-- NOTE: After updating app code to use order_items instead of
-- items_detail, remove the jsonb column with:
--
--   ALTER TABLE public.orders DROP COLUMN items_detail;
--
-- Do NOT drop it in this migration — the application still reads it.
-- ------------------------------------------------------------
