-- ============================================================
-- Migration: 010 — Payment Attempts Table (Future-Ready)
-- Status: DEFERRED — not yet needed, but schema is prepared.
-- Uncomment and apply when payment history tracking is required.
-- ============================================================

-- CREATE TYPE public.payment_status AS ENUM (
--   'pending',
--   'processing',
--   'paid',
--   'failed',
--   'refunded',
--   'disputed',
--   'cancelled'
-- );

-- CREATE TYPE public.payment_provider AS ENUM (
--   'abacatepay',
--   'stripe',
--   'pagseguro'
-- );

-- CREATE TABLE public.payment_attempts (
--   id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   order_id         bigint                NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
--   provider         public.payment_provider NOT NULL DEFAULT 'abacatepay',
--   external_id      text,              -- Gateway checkout/transaction ID
--   status           public.payment_status NOT NULL DEFAULT 'pending',
--   amount           numeric(12,2)       NOT NULL,
--   currency         char(3)             NOT NULL DEFAULT 'BRL',
--   payment_method   text,              -- 'PIX', 'CARD', etc.
--   checkout_url     text,
--   raw_response     jsonb,             -- Full gateway response for debugging
--   paid_at          timestamptz,
--   created_at       timestamptz         NOT NULL DEFAULT now(),
--   updated_at       timestamptz         NOT NULL DEFAULT now(),
--
--   CONSTRAINT payment_attempts_amount_positive CHECK (amount > 0)
-- );

-- CREATE INDEX idx_payment_attempts_order_id   ON public.payment_attempts (order_id);
-- CREATE INDEX idx_payment_attempts_external_id ON public.payment_attempts (external_id) WHERE external_id IS NOT NULL;
-- CREATE INDEX idx_payment_attempts_status      ON public.payment_attempts (status);

-- ALTER TABLE public.payment_attempts ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY payment_attempts_select
--   ON public.payment_attempts FOR SELECT TO authenticated
--   USING (
--     EXISTS (
--       SELECT 1 FROM public.orders
--       WHERE orders.id = payment_attempts.order_id
--         AND (orders.customer_id = auth.uid() OR public.is_admin())
--     )
--   );

-- CREATE POLICY payment_attempts_insert_admin
--   ON public.payment_attempts FOR INSERT TO authenticated
--   WITH CHECK (public.is_admin());

-- CREATE TRIGGER payment_attempts_updated_at
--   BEFORE UPDATE ON public.payment_attempts
--   FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- GRANT SELECT ON public.payment_attempts TO authenticated;
-- GRANT INSERT, UPDATE ON public.payment_attempts TO authenticated;
-- GRANT USAGE, SELECT ON SEQUENCE payment_attempts_id_seq TO authenticated;
