-- ============================================================
-- Migration: 012 — Payment Attempts Table
-- Tracks every payment gateway interaction for observability,
-- idempotency checks, and reconciliation.
-- ============================================================

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
    CREATE TYPE public.payment_status AS ENUM (
      'pending',
      'processing',
      'paid',
      'failed',
      'refunded',
      'disputed',
      'cancelled'
    );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_provider') THEN
    CREATE TYPE public.payment_provider AS ENUM (
      'abacatepay',
      'stripe',
      'pagseguro'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.payment_attempts (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id         bigint                        NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  provider         public.payment_provider       NOT NULL DEFAULT 'abacatepay',
  external_id      text,
  status           public.payment_status         NOT NULL DEFAULT 'pending',
  amount           numeric(12,2)                 NOT NULL,
  currency         char(3)                       NOT NULL DEFAULT 'BRL',
  payment_method   text,
  checkout_url     text,
  raw_response     jsonb,
  paid_at          timestamptz,
  created_at       timestamptz                   NOT NULL DEFAULT now(),
  updated_at       timestamptz                   NOT NULL DEFAULT now(),

  CONSTRAINT payment_attempts_amount_positive CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_payment_attempts_order_id    ON public.payment_attempts (order_id);
CREATE INDEX IF NOT EXISTS idx_payment_attempts_external_id ON public.payment_attempts (external_id) WHERE external_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_attempts_status      ON public.payment_attempts (status);

ALTER TABLE public.payment_attempts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS payment_attempts_select ON public.payment_attempts;
CREATE POLICY payment_attempts_select
  ON public.payment_attempts FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.orders
      WHERE orders.id = payment_attempts.order_id
        AND (orders.customer_id = auth.uid() OR public.is_admin())
    )
  );

DROP TRIGGER IF EXISTS payment_attempts_updated_at ON public.payment_attempts;
CREATE TRIGGER payment_attempts_updated_at
  BEFORE UPDATE ON public.payment_attempts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

GRANT SELECT ON public.payment_attempts TO authenticated;
GRANT INSERT, UPDATE ON public.payment_attempts TO service_role;
