-- ============================================================
-- Adesil Website — Migration inicial completa
-- Gerado em: 2026-05-12
-- ============================================================

-- ------------------------------------------------------------
-- 1. ENUMS
-- ------------------------------------------------------------

CREATE TYPE public.user_role AS ENUM ('admin', 'customer');

CREATE TYPE public.order_status AS ENUM ('pending', 'processing', 'shipped', 'delivered');


-- ------------------------------------------------------------
-- 2. TABELAS
-- (Ordem respeita as FK: categories → products, profiles → orders)
-- ------------------------------------------------------------

CREATE TABLE public.categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text        NOT NULL,
  description text
);

CREATE TABLE public.products (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text           NOT NULL,
  description    text,
  price          numeric        NOT NULL,
  original_price numeric,
  image          text,
  tags           text,
  created_at     timestamptz    NOT NULL DEFAULT now(),
  category       bigint         REFERENCES public.categories(id),
  is_featured    boolean        NOT NULL DEFAULT false
);

CREATE TABLE public.profiles (
  id                  uuid PRIMARY KEY REFERENCES auth.users(id),
  name                text           NOT NULL,
  email               text           NOT NULL,
  role                public.user_role NOT NULL DEFAULT 'customer',
  created_at          timestamptz    NOT NULL DEFAULT now(),
  updated_at          timestamptz    NOT NULL DEFAULT now(),
  document            text,
  company_name        text,
  shipping_zipcode    text,
  shipping_street     text,
  shipping_number     text,
  shipping_complement text,
  shipping_city       text,
  shipping_state      text,
  shipping_country    text           DEFAULT 'BR'
);

CREATE TABLE public.orders (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date                date           NOT NULL,
  status              public.order_status NOT NULL DEFAULT 'pending',
  total               numeric        NOT NULL,
  items               integer        NOT NULL DEFAULT 1,
  customer            text           NOT NULL,
  created_at          timestamptz    NOT NULL DEFAULT now(),
  customer_id         uuid           REFERENCES public.profiles(id),
  customer_email      text,
  document            text,
  billing_name        text,
  company_name        text,
  shipping_street     text,
  shipping_number     text,
  shipping_complement text,
  shipping_city       text,
  shipping_state      text,
  shipping_country    text           DEFAULT 'BR',
  shipping_cost       numeric,
  items_detail        jsonb,
  shipping_zipcode    text
);

CREATE TABLE public.contact_messages (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text        NOT NULL,
  email      text        NOT NULL,
  phone      text        NOT NULL,
  message    text        NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);


-- ------------------------------------------------------------
-- 3. ÍNDICES
-- ------------------------------------------------------------

CREATE INDEX idx_products_is_featured_created_at ON public.products (is_featured, created_at DESC);

CREATE INDEX idx_orders_date   ON public.orders (date DESC);
CREATE INDEX idx_orders_status ON public.orders (status);

CREATE INDEX idx_profiles_email ON public.profiles (email);
CREATE INDEX idx_profiles_role  ON public.profiles (role);


-- ------------------------------------------------------------
-- 4. FUNÇÕES
-- ------------------------------------------------------------

-- Verifica se o usuário autenticado é admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$$;

-- Atualiza updated_at automaticamente
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Cria profile automaticamente ao cadastrar usuário
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    NEW.email,
    'customer'
  );
  RETURN NEW;
END;
$$;

-- Permissão para o role de auth executar o trigger
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO supabase_auth_admin;
GRANT INSERT ON public.profiles TO supabase_auth_admin;


-- ------------------------------------------------------------
-- 5. TRIGGERS
-- ------------------------------------------------------------

-- Atualiza profiles.updated_at em cada UPDATE
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Cria profile quando um novo usuário é cadastrado no Auth
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ------------------------------------------------------------
-- 6. ROW LEVEL SECURITY (RLS)
-- ------------------------------------------------------------

ALTER TABLE public.categories      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- ---- categories ----

CREATE POLICY public_read_categories
  ON public.categories FOR SELECT TO public
  USING (true);

CREATE POLICY admin_insert_categories
  ON public.categories FOR INSERT TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY admin_update_categories
  ON public.categories FOR UPDATE TO authenticated
  USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY admin_delete_categories
  ON public.categories FOR DELETE TO authenticated
  USING (is_admin());

-- ---- products ----

CREATE POLICY public_read_products
  ON public.products FOR SELECT TO public
  USING (true);

CREATE POLICY admin_insert_products
  ON public.products FOR INSERT TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY admin_update_products
  ON public.products FOR UPDATE TO authenticated
  USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY admin_delete_products
  ON public.products FOR DELETE TO authenticated
  USING (is_admin());

-- ---- profiles ----

CREATE POLICY user_select_own_profile
  ON public.profiles FOR SELECT TO authenticated
  USING (id = auth.uid());

CREATE POLICY user_update_own_profile
  ON public.profiles FOR UPDATE TO authenticated
  USING (id = auth.uid())
  WITH CHECK (
    (id = auth.uid()) AND
    (role = (SELECT p.role FROM profiles p WHERE p.id = auth.uid()))
  );

CREATE POLICY admin_select_all_profiles
  ON public.profiles FOR SELECT TO authenticated
  USING (is_admin());

CREATE POLICY admin_update_any_profile
  ON public.profiles FOR UPDATE TO authenticated
  USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY admin_delete_any_profile
  ON public.profiles FOR DELETE TO authenticated
  USING (is_admin());

-- ---- orders ----

CREATE POLICY "Users can insert own orders"
  ON public.orders FOR INSERT TO public
  WITH CHECK ((auth.role() = 'authenticated') AND (customer_id = auth.uid()));

CREATE POLICY "Users can select own orders"
  ON public.orders FOR SELECT TO public
  USING ((auth.role() = 'authenticated') AND (customer_id = auth.uid()));

CREATE POLICY "Users can update own orders"
  ON public.orders FOR UPDATE TO public
  USING ((auth.role() = 'authenticated') AND (customer_id = auth.uid()))
  WITH CHECK ((auth.role() = 'authenticated') AND (customer_id = auth.uid()));

CREATE POLICY "Users can delete own orders"
  ON public.orders FOR DELETE TO public
  USING ((auth.role() = 'authenticated') AND (customer_id = auth.uid()));

CREATE POLICY admin_select_orders
  ON public.orders FOR SELECT TO authenticated
  USING (is_admin());

CREATE POLICY admin_update_orders
  ON public.orders FOR UPDATE TO authenticated
  USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY admin_delete_orders
  ON public.orders FOR DELETE TO authenticated
  USING (is_admin());

CREATE POLICY auth_read_orders
  ON public.orders FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Admin can select all orders"
  ON public.orders FOR SELECT TO public
  USING (
    (auth.role() = 'authenticated') AND
    (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  );

CREATE POLICY "Admin can update all orders"
  ON public.orders FOR UPDATE TO public
  USING (
    (auth.role() = 'authenticated') AND
    (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  )
  WITH CHECK (
    (auth.role() = 'authenticated') AND
    (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  );

CREATE POLICY "Admin can delete all orders"
  ON public.orders FOR DELETE TO public
  USING (
    (auth.role() = 'authenticated') AND
    (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  );

-- ---- contact_messages ----

CREATE POLICY "Allow public insert contact messages"
  ON public.contact_messages FOR INSERT TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "Allow admin read contact messages"
  ON public.contact_messages FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );


-- ------------------------------------------------------------
-- 7. GRANTS
-- (RLS não basta — o PostgreSQL exige GRANT explícito por role)
-- ------------------------------------------------------------

GRANT USAGE ON SCHEMA public TO anon, authenticated;

-- Leitura pública (visitantes sem login)
GRANT SELECT ON public.categories TO anon, authenticated;
GRANT SELECT ON public.products   TO anon, authenticated;

-- Escrita em categories e products (RLS restringe a admins)
GRANT INSERT, UPDATE, DELETE ON public.categories TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.products   TO authenticated;

-- Operações de usuário autenticado
GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders           TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles         TO authenticated;
GRANT SELECT, INSERT                 ON public.contact_messages TO anon, authenticated;

-- Sequências IDENTITY (necessário para INSERT retornar o ID gerado)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
