CREATE TABLE IF NOT EXISTS public.coupons (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        text NOT NULL UNIQUE,
  type        text NOT NULL CHECK (type IN ('percent', 'fixed')),
  value       numeric(10,2) NOT NULL CHECK (value > 0),
  description text,
  is_active   boolean NOT NULL DEFAULT true,
  max_uses    integer,
  uses_count  integer NOT NULL DEFAULT 0,
  expires_at  timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER coupons_updated_at
  BEFORE UPDATE ON public.coupons
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

CREATE POLICY coupons_admin_all ON public.coupons
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY coupons_public_read ON public.coupons
  FOR SELECT TO anon, authenticated USING (is_active = true);

INSERT INTO public.coupons (code, type, value, description) VALUES
  ('ADESIL10', 'percent', 10, '10% de desconto'),
  ('FRETE',    'percent', 15, 'Desconto de frete (15%)')
ON CONFLICT (code) DO NOTHING;
